[package]
name = "mtc-verifier"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = "7.1.3"
log = "0.4.22"
sha2 = "0.10.8"
rustls-pki-types = "1.10.0"
pqcrypto-mldsa = "0.1.0"
pqcrypto-traits = "0.3.5"


[dev-dependencies]
env_logger = "0.11.5"